apiVersion: v1
kind: PersistentVolume                        # Create a PV
metadata:
  name: mongo-pv
  namespace: ms-service
  labels:
    type: local
    app: mongo
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:                                   # hostPath PersistentVolume is used for development and testing. It uses a file/directory on the Node to emulate network-attached storage
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: ms-service
  labels:
    app: mongo
spec:

  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteMany