apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: ms-service
  labels:
    app: mongo
spec:
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    app: mongo